#[allow(dead_code)]
#[derive(PartialEq, Eq, Hash, Debug)]
pub enum Key {
    Unknown,
    Space,
    Apostrophe,
    Comma,
    Minus,
    Period,
    Slash,
    Number0,
    Number1,
    Number2,
    Number3,
    Number4,
    Number5,
    Number6,
    Number7,
    Number8,
    Number9,
    Semicolon,
    Equal,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftBracket,
    Backslash,
    RightBracket,
    GraveAccent,
    Escape,
    Enter,
    Tab,
    Backspace,
    Insert,
    Delete,
    Right,
    Left,
    Down,
    Up,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadDecimal,
    NumpadDivide,
    NumpadMultiply,
    NumpadSubtract,
    NumpadAdd,
    NumpadEnter,
    NumpadEqual,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    Menu,
}

impl Key {
    pub fn to_sdl2(&self) -> Option<sdl2::keyboard::Scancode> {
        match *self {
            Key::Space => Some(sdl2::keyboard::Scancode::Space),
            Key::Apostrophe => Some(sdl2::keyboard::Scancode::Apostrophe),
            Key::Comma => Some(sdl2::keyboard::Scancode::Comma),
            Key::Minus => Some(sdl2::keyboard::Scancode::Minus),
            Key::Period => Some(sdl2::keyboard::Scancode::Period),
            Key::Slash => Some(sdl2::keyboard::Scancode::Slash),
            Key::Number0 => Some(sdl2::keyboard::Scancode::Num0),
            Key::Number1 => Some(sdl2::keyboard::Scancode::Num1),
            Key::Number2 => Some(sdl2::keyboard::Scancode::Num2),
            Key::Number3 => Some(sdl2::keyboard::Scancode::Num3),
            Key::Number4 => Some(sdl2::keyboard::Scancode::Num4),
            Key::Number5 => Some(sdl2::keyboard::Scancode::Num5),
            Key::Number6 => Some(sdl2::keyboard::Scancode::Num6),
            Key::Number7 => Some(sdl2::keyboard::Scancode::Num7),
            Key::Number8 => Some(sdl2::keyboard::Scancode::Num8),
            Key::Number9 => Some(sdl2::keyboard::Scancode::Num9),
            Key::Semicolon => Some(sdl2::keyboard::Scancode::Semicolon),
            Key::Equal => Some(sdl2::keyboard::Scancode::Equals),
            Key::A => Some(sdl2::keyboard::Scancode::A),
            Key::B => Some(sdl2::keyboard::Scancode::B),
            Key::C => Some(sdl2::keyboard::Scancode::C),
            Key::D => Some(sdl2::keyboard::Scancode::D),
            Key::E => Some(sdl2::keyboard::Scancode::E),
            Key::F => Some(sdl2::keyboard::Scancode::F),
            Key::G => Some(sdl2::keyboard::Scancode::G),
            Key::H => Some(sdl2::keyboard::Scancode::H),
            Key::I => Some(sdl2::keyboard::Scancode::I),
            Key::J => Some(sdl2::keyboard::Scancode::J),
            Key::K => Some(sdl2::keyboard::Scancode::K),
            Key::L => Some(sdl2::keyboard::Scancode::L),
            Key::M => Some(sdl2::keyboard::Scancode::M),
            Key::N => Some(sdl2::keyboard::Scancode::N),
            Key::O => Some(sdl2::keyboard::Scancode::O),
            Key::P => Some(sdl2::keyboard::Scancode::P),
            Key::Q => Some(sdl2::keyboard::Scancode::Q),
            Key::R => Some(sdl2::keyboard::Scancode::R),
            Key::S => Some(sdl2::keyboard::Scancode::S),
            Key::T => Some(sdl2::keyboard::Scancode::T),
            Key::U => Some(sdl2::keyboard::Scancode::U),
            Key::V => Some(sdl2::keyboard::Scancode::V),
            Key::W => Some(sdl2::keyboard::Scancode::W),
            Key::X => Some(sdl2::keyboard::Scancode::X),
            Key::Y => Some(sdl2::keyboard::Scancode::Y),
            Key::Z => Some(sdl2::keyboard::Scancode::Z),
            Key::LeftBracket => Some(sdl2::keyboard::Scancode::LeftBracket),
            Key::Backslash => Some(sdl2::keyboard::Scancode::Backslash),
            Key::RightBracket => Some(sdl2::keyboard::Scancode::RightBracket),
            Key::GraveAccent => Some(sdl2::keyboard::Scancode::Grave),
            Key::Escape => Some(sdl2::keyboard::Scancode::Escape),
            Key::Enter => Some(sdl2::keyboard::Scancode::Return),
            Key::Tab => Some(sdl2::keyboard::Scancode::Tab),
            Key::Backspace => Some(sdl2::keyboard::Scancode::Backspace),
            Key::Insert => Some(sdl2::keyboard::Scancode::Insert),
            Key::Delete => Some(sdl2::keyboard::Scancode::Delete),
            Key::Right => Some(sdl2::keyboard::Scancode::Right),
            Key::Left => Some(sdl2::keyboard::Scancode::Left),
            Key::Down => Some(sdl2::keyboard::Scancode::Down),
            Key::Up => Some(sdl2::keyboard::Scancode::Up),
            Key::PageUp => Some(sdl2::keyboard::Scancode::PageUp),
            Key::PageDown => Some(sdl2::keyboard::Scancode::PageDown),
            Key::Home => Some(sdl2::keyboard::Scancode::Home),
            Key::End => Some(sdl2::keyboard::Scancode::End),
            Key::CapsLock => Some(sdl2::keyboard::Scancode::CapsLock),
            Key::ScrollLock => Some(sdl2::keyboard::Scancode::ScrollLock),
            Key::NumLock => Some(sdl2::keyboard::Scancode::NumLockClear),
            Key::PrintScreen => Some(sdl2::keyboard::Scancode::PrintScreen),
            Key::Pause => Some(sdl2::keyboard::Scancode::Pause),
            Key::F1 => Some(sdl2::keyboard::Scancode::F1),
            Key::F2 => Some(sdl2::keyboard::Scancode::F2),
            Key::F3 => Some(sdl2::keyboard::Scancode::F3),
            Key::F4 => Some(sdl2::keyboard::Scancode::F4),
            Key::F5 => Some(sdl2::keyboard::Scancode::F5),
            Key::F6 => Some(sdl2::keyboard::Scancode::F6),
            Key::F7 => Some(sdl2::keyboard::Scancode::F7),
            Key::F8 => Some(sdl2::keyboard::Scancode::F8),
            Key::F9 => Some(sdl2::keyboard::Scancode::F9),
            Key::F10 => Some(sdl2::keyboard::Scancode::F10),
            Key::F11 => Some(sdl2::keyboard::Scancode::F11),
            Key::F12 => Some(sdl2::keyboard::Scancode::F12),
            Key::F13 => Some(sdl2::keyboard::Scancode::F13),
            Key::F14 => Some(sdl2::keyboard::Scancode::F14),
            Key::F15 => Some(sdl2::keyboard::Scancode::F15),
            Key::F16 => Some(sdl2::keyboard::Scancode::F16),
            Key::F17 => Some(sdl2::keyboard::Scancode::F17),
            Key::F18 => Some(sdl2::keyboard::Scancode::F18),
            Key::F19 => Some(sdl2::keyboard::Scancode::F19),
            Key::F20 => Some(sdl2::keyboard::Scancode::F20),
            Key::F21 => Some(sdl2::keyboard::Scancode::F21),
            Key::F22 => Some(sdl2::keyboard::Scancode::F22),
            Key::F23 => Some(sdl2::keyboard::Scancode::F23),
            Key::F24 => Some(sdl2::keyboard::Scancode::F24),
            Key::Numpad0 => Some(sdl2::keyboard::Scancode::Kp0),
            Key::Numpad1 => Some(sdl2::keyboard::Scancode::Kp1),
            Key::Numpad2 => Some(sdl2::keyboard::Scancode::Kp2),
            Key::Numpad3 => Some(sdl2::keyboard::Scancode::Kp3),
            Key::Numpad4 => Some(sdl2::keyboard::Scancode::Kp4),
            Key::Numpad5 => Some(sdl2::keyboard::Scancode::Kp5),
            Key::Numpad6 => Some(sdl2::keyboard::Scancode::Kp6),
            Key::Numpad7 => Some(sdl2::keyboard::Scancode::Kp7),
            Key::Numpad8 => Some(sdl2::keyboard::Scancode::Kp8),
            Key::Numpad9 => Some(sdl2::keyboard::Scancode::Kp9),
            Key::NumpadDecimal => Some(sdl2::keyboard::Scancode::KpDecimal),
            Key::NumpadDivide => Some(sdl2::keyboard::Scancode::KpDivide),
            Key::NumpadMultiply => Some(sdl2::keyboard::Scancode::KpMultiply),
            Key::NumpadSubtract => Some(sdl2::keyboard::Scancode::KpMinus),
            Key::NumpadAdd => Some(sdl2::keyboard::Scancode::KpPlus),
            Key::NumpadEnter => Some(sdl2::keyboard::Scancode::KpEnter),
            Key::NumpadEqual => Some(sdl2::keyboard::Scancode::KpEquals),
            Key::LeftShift => Some(sdl2::keyboard::Scancode::LShift),
            Key::LeftControl => Some(sdl2::keyboard::Scancode::LCtrl),
            Key::LeftAlt => Some(sdl2::keyboard::Scancode::LAlt),
            Key::LeftSuper => Some(sdl2::keyboard::Scancode::LGui),
            Key::RightShift => Some(sdl2::keyboard::Scancode::RShift),
            Key::RightControl => Some(sdl2::keyboard::Scancode::RCtrl),
            Key::RightAlt => Some(sdl2::keyboard::Scancode::RAlt),
            Key::RightSuper => Some(sdl2::keyboard::Scancode::RGui),
            Key::Menu => Some(sdl2::keyboard::Scancode::Menu),

            _ => None,
        }
    }
}
